// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8JQ0sCwGPJ-dzXbonTAsBWp3zEJPgUa8',
    appId: '1:408418106565:web:c9f7e5d61bf188aab6c4ac',
    messagingSenderId: '408418106565',
    projectId: 'humsafar-a4ec5',
    authDomain: 'humsafar-a4ec5.firebaseapp.com',
    storageBucket: 'humsafar-a4ec5.firebasestorage.app',
    measurementId: 'G-WLC1Y66JFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7_Z2UkAOQ6tgUOXCY4zdoW3uXuE68oY',
    appId: '1:408418106565:android:a9be9b294924d5d2b6c4ac',
    messagingSenderId: '408418106565',
    projectId: 'humsafar-a4ec5',
    storageBucket: 'humsafar-a4ec5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8JQ0sCwGPJ-dzXbonTAsBWp3zEJPgUa8',
    appId: '1:408418106565:web:3b648eae18795d72b6c4ac',
    messagingSenderId: '408418106565',
    projectId: 'humsafar-a4ec5',
    authDomain: 'humsafar-a4ec5.firebaseapp.com',
    storageBucket: 'humsafar-a4ec5.firebasestorage.app',
    measurementId: 'G-Q3VZ1KV159',
  );
}
